apfm_obstacle_avoidance:
  attraction_scaling_factor:       30
  obstacle_scaling_factor_dynamic: 2000
  obstacle_scaling_factor_static:  300000
  scaling_factor_emergency:        2000
  robot_domain_radius:             1.4
  safe_distance:                   9.82
  # obstacle_influence_range:        15

scenario_controller:
  scenario:               0         # Defina o número do cenário conforme necessário
  goal_x:                 70.0            # Defina a posição do objetivo em X
  goal_y:                 70.0            # Defina a posição do objetivo em Y
  goal_publish_rate:      1
  obstacle_publish_rate:  10
  robot_publish_rate:     10